#!/bin/bash

set -e

# from here: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

sudo apt-get -y install autoconf automake build-essential libass-dev libfreetype6-dev libgpac-dev libtheora-dev libtool libvorbis-dev pkg-config texi2html zlib1g-dev unzip yasm libmp3lame-dev

SOURCES=`pwd`/ffmpeg_sources
BUILD=`pwd`/ffmpeg_build
BIN=`pwd`/bin
DEB_OUT=`pwd`/deb

# build yasm

mkdir -p $SOURCES
mkdir -p $DEB_OUT

cd $SOURCES
wget http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
tar xzvf yasm-1.3.0.tar.gz
cd yasm-1.3.0
./configure --prefix="$BUILD" --bindir="$BIN"
make
make install
make distclean

# build libfdk_aac

cd $SOURCES
wget -O fdk-aac.tar.gz https://github.com/mstorsjo/fdk-aac/tarball/master
tar xzvf fdk-aac.tar.gz
cd mstorsjo-fdk-aac*
autoreconf -fiv
./configure --prefix="$BUILD" --disable-shared
make
make install
make distclean

# build opus

cd $SOURCES
wget http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz
tar xzvf opus-1.1.tar.gz
cd opus-1.1
./configure --prefix="$BUILD" --disable-shared
make
make install
make clean

# build

cd $SOURCES
wget http://ffmpeg.org/releases/ffmpeg-2.8.tar.bz2
tar xjvf ffmpeg-2.8.tar.bz2
cd ffmpeg-2.8
PATH="$BIN:$PATH" PKG_CONFIG_PATH="$BUILD/lib/pkgconfig" ./configure \
  --prefix="$BUILD" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$BUILD/include" \
  --extra-ldflags="-L$BUILD/lib" \
  --bindir="$BIN" \
  --enable-gpl \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libtheora \
  --enable-libvorbis \
  --enable-nonfree
PATH="$BIN:$PATH" make
make install
make distclean

# create debian

gem list -i fpm || sudo gem install fpm


# take everything in $BIN, and slap it in /usr/local/bin
cd $BIN

fpm -s dir -t deb -n ffmpeg-2.8 -v 2.8.0  --prefix /usr/local/bin -p "$DEB_OUT/ffmpeg-2.8.deb" -d libxcb-shm0 -d libxcb-xfixes0 -d libxcb-shape0 -d libass4 -d libvdpau1 -d libsdl1.2debian .

